spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    url: jdbc:postgresql://localhost:5432/study
    password: root

  application:
    name: study

  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /study-swagger-ui

jwt:
  access-token-expiration: 3600000  # 1시간 (ms 기준)
  refresh-token-expiration-days: 7